### ISSUE TITLE
long file name issue of recently opened file

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#109]
If the name of a file is too long,when the mouse move to "recently opened file", it becomes full screen,which doesn't look good

**Comment by godly-devotion** [comment]
Hmm could you show me your example?

**Comment by amazingfate** [comment]
my printscreen doesn't work, you can rename a file to a long name or move it to a long location to test

**Comment by u8sand** [comment]
We can simple trim file names at a certain length--what do you think is a good length and do we trim the front or the end? or the middle..?

**Comment by godly-devotion** [comment]
@u8sand I recommend trimming from the middle (TV name is usually in the front & episode num is in the back). however trim the folder name and the filename separately.

**Comment by amazingfate** [comment]
I think we can just show the file name, not the full location, since the single file name can't be so long

**Comment by u8sand** [comment]
Well we only show the parent directory. Most systems have a 256 character
limit.
I was thinking it might be good to keep the parent directory (or trim it
from the end); and trim the file name in a non-intrusive way. we might want
to do a smart trim which looks for the episode number/markers and trims
those then the end of the filename.

**Comment by godly-devotion** [comment]
@u8sand while I think trimming the parent directory name from the end is fine, I still recommend trimming a long file name from the center. although it may be cool to smart trim, it may lead to more confusion for the user.

**Comment by u8sand** [comment]
The issue with simply trimming from the center is with a video which has
sub prefix and episode postfix

[long translator name] long title season 3 movie 3 episode 1

the center here is the only important part.

**Comment by godly-devotion** [comment]
Hmm I did some sampling with some files I have, I agree with @u8sand. So both the parent directory and the file name should trim from the end (except for the file extension "[long translator name] title 3...mkv").
