### ISSUE TITLE
Subtitles not working

### ISSUE THREAD

**Issue by bretanac93** [u8sand/Baka-MPlayer#110]
Hi, the subtitles aren´t working in the last version, check this out.

**Comment by amazingfate** [comment]
if you use windows, you can try my build: https://github.com/amazingfate/baka-build/releases/download/git%4020150402/Baka-MPlayer_x86_64.zip

**Comment by u8sand** [comment]
Also, please see issue #88

**Comment by godly-devotion** [comment]
Fixed with latest version.
