### ISSUE TITLE
Make the media info show fps?

### ISSUE THREAD

**Issue by dragons4life** [u8sand/Baka-MPlayer#111]
<img src='http://a.pomf.se/jrvzif.png'/>

**Comment by u8sand** [comment]
@dragons4life 
This is in our plan moving forward; the main issue it isn't "simple" is because mpv tells us:

       fps    Container FPS. This can easily contain bogus values. For  videos
              that  use  modern  container  formats or video codecs, this will
              often be incorrect.

**Comment by godly-devotion** [comment]
@u8sand we'd use `estimated-vf-fps`. "Estimated/measured FPS of the video filter chain output. (If no filters are used, this corresponds to decoder output.) This uses the average of the 10 past frame durations to calculate the FPS." However this is real time info so Baka's overlay system will need to have the ability to update info real-time (another thing in plan).

**Comment by godly-devotion** [comment]
@u8sand also I added some info pertaining showing info as overlay in wf. The general idea came from here https://github.com/mpv-player/mpv/issues/1760

**Comment by u8sand** [comment]
You'll note that there is a working implementation here: 9156294734a2b42851c89b9b1233bfcac0f0c125
Most likely today I'll make it more efficient and merge it to master.

**Comment by dragons4life** [comment]
Thanks.

**Comment by u8sand** [comment]
Merged b110b3d24dd1141060ac6452b6cf9ca0fe201cc9
