### ISSUE TITLE
Some advice about playlist.

### ISSUE THREAD

**Issue by alienhjy** [u8sand/Baka-MPlayer#113]
1、Please add support for remember the last position.
For 2.0.2, when I open a video(I only try with video), it always play the video from the head...
2、It will be better if baka can support "multi playlist" for locale video file.
Just like PPTV player. For PPTV, when I open a video file, it will add all video on the same dir to current playlist, like baka does now. But when I open a new video file on another dir, the old playlist will not be deleted. The old playlist will be named by the dir, and videos on the new dir will be add to a new playlist, named by the new dir too. With this, I can use different playlist for different TV series...

**Comment by u8sand** [comment]
@alienhjy 
With regards to 1. does Ctrl+Z (which opens the last played file) not reload that file?
And for 2. I'm just not really following the suggestion, could you clarify? From what I understand you want baka to have directory support for having multiple playlists at once. Why not just open another baka? I just think turning baka's playlist into a file manager is not really useful.

**Comment by alienhjy** [comment]
@u8sand 
For 1. Ctrl+Z could only open the last played file, but can't start with the last position. It will play the last file from the beginning of its.
For 2. open another baka can't store this two or more playlist. It will empty all of the old playlist when we open baka next time...
For understanding what i saied, why not try PPTV?

**Comment by u8sand** [comment]
Ok, for the last position, it is a feature in our scope so you'll certainly
see it implemented in the future.

I'll look into PPTV.  Thank you for your feedback!

**Comment by alienhjy** [comment]
@u8sand Thanks for your work~

**Comment by godly-devotion** [comment]
Completed. Recently Opened items have their last position saved now.
