### ISSUE TITLE
logo not show in awesome wm

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#118]
we only install baka-mplayer.svg to /usr/share/pixmaps, we should also install icons to /usr/share/icons/hicolor
this also cause big icon in app menu in xfce

**Comment by u8sand** [comment]
I'll put a copy in `/usr/share/icons/hicolor/scalable/apps/` I'm not entirely familiar with this folder, if I should be putting in all the sizes to the other folders just tell me.
