### ISSUE TITLE
Feature Request > Preferences > Key Bindings > Mute

### ISSUE THREAD

**Issue by ConundrumAdInfinitum** [u8sand/Baka-MPlayer#120]
Hello Developers,

I think it would be useful if you could add a "Mute" feature, accessible via Key Bindings, to Baka MPlayer.

**Comment by u8sand** [comment]
You can make your own! Use the command  `volume 0`

**Comment by ConundrumAdInfinitum** [comment]
I figured out how to add the command to the Key Bindings, however the results are not as I would have expected. I suppose I am hoping for a "Toggle Mute" function.





        Sent by Outlook for Android




On Wed, Apr 15, 2015 at 9:14 AM -0700, "Daniel Clarke" <notifications@github.com> wrote:










You can make your own! Use the command  `volume 0`

On Apr 15, 2015 6:32 AM, "ConundrumAdInfinitum" <notifications@github.com>

wrote:

**Comment by godly-devotion** [comment]
@ConundrumAdInfinitum hey you're probably looking for `mpv cycle mute`.

@u8sand I think we should add mute ability by default. I'll think about how it should look/work.

**Comment by ConundrumAdInfinitum** [comment]
Thanks for provideing the command code, I was able to set a Key Binding for
a "Toggle Mute" function, I agree it should be in there by default.

**Comment by u8sand** [comment]
@godly-devotion Have you thought of a way to add mute as a default feature?

**Comment by u8sand** [comment]
Fixed with 4ab04610be1933ac0960a3dd3faf7642b4a3cd78
