### ISSUE TITLE
Perhaps include peerflix to stream from torrents?

### ISSUE THREAD

**Issue by Chaquator** [u8sand/Baka-MPlayer#121]
Title says it all, really.
Would be nice to watch torrent streams like I could watch YouTube.
Perhaps have a setting to choose a the folder for the temporary files, too. The way I did it was by making a symlink to where it'd normally place those files (on my SSD), but I'm sure you could do it within the js files themselves.

**Comment by u8sand** [comment]
I feel like this is something which should be added into mpv (and then it would naturally be added to baka). I'll look into making the change to mpv.

**Comment by Chaquator** [comment]
true true
no reason to have to increase bulk by adding node and all the modules and dependencies and all

**Comment by VeralianIV** [comment]
Isn't this already possible with a torrent client by prioritizing the file order and then opening it with baka player?

**Comment by godly-devotion** [comment]
@VeralianIV As you say it is already possible. Many torrent clients allow you to download the file in sequential order so you can watch while its downloading. And as `mpv` is really good at playing downloading/broken files Baka MPlayer is naturally really good too. Maybe we'll add Peerflix support in the future but that is low priority as of now.
