### ISSUE TITLE
Possible to use MadVR or some sort of motion interpolation?

### ISSUE THREAD

**Issue by Chaquator** [u8sand/Baka-MPlayer#124]
Better yet, is there a way to change the DirectShow thing in the settings?

**Comment by godly-devotion** [comment]
We are planning to add motion interpolation option under Preferences. In the meantime try adding the line `vo=opengl-hq:interpolation` under the `[mpv] ` line in `bakamplayer.ini`.

**Comment by Chaquator** [comment]
Cool!
Is that kind of motion interpolation just fading between frames rapidly or actual interpolation?

**Comment by dragons4life** [comment]
A little off-topic but does MPV have "debanding" like madVR?
<img src='http://i.imgur.com/bZKs3KU.png'/>

Anyways to add it to to Bakam?

**Comment by godly-devotion** [comment]
@Chaquator @dragons4life I see. I recommend asking the `mpv-player/mpv` folks directly about these two questions.

And just to reiterate, you can set mpv options (https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst) into the `bakamplayer.ini` settings file under the `[mpv]` section. There are a lot of stuff you can set, so I recommend find & search first before asking them also.

**Comment by godly-devotion** [comment]
Fixed via 39665f1

**Comment by Chaquator** [comment]
based
