### ISSUE TITLE
Is there a PPA for Ubuntu based system？

### ISSUE THREAD

**Issue by laichiaheng** [u8sand/Baka-MPlayer#125]
Is there a PPA for Ubuntu based system?
It is much easier to install it!

**Comment by laichiaheng** [comment]
It said that I didn't have a xcb plugin. What is it?

**Comment by amazingfate** [comment]
somebody has done this: https://launchpad.net/~mc3man/+archive/ubuntu/libmpv1
I don't use ubuntu so you can contact Doug McMahon on launchpad if you have any problem.

**Comment by godly-devotion** [comment]
I've actually contacted @mc4man and is waiting for his response.

**Comment by mc4man** [comment]
Well - 
the ppa mentioned above is a staging ppa, really not meant for general use as it depends on other ppa's, one of which is a personal 14.04 ppa that while useable will 'break' at times.
The issues concerning a ppa for baka are these - 
1. support for Ubuntu releases other than lts releases is time consuming & of limited value as after 9 months no more buids in a ppa can be done.
2. There is the question for 14.04 of whether to provide a mpv build with libmpv enabled using a static linked ffmpeg, this I'm not keen on.
So - for 14.04 only - this ppa has 
a standalone libmpv build
a shared ffmpeg build
a baka-mplayer build
As builds of all three are tested over time in the staging/my personal ppa  they are then moved into this ppa for general use. (there will be a new baka build shortly
If interested please read the ppa fully before deciding to use & please don't offer any other user a command to use this ppa without the suggestion to read ppa page  first.
https://launchpad.net/~mc3man/+archive/ubuntu/testing6

For 15.04 users baka is in this ppa, please note that there will only be Maybe 1 more build of the included packages before 15.04 EOL next Feb.
In this ppa libmpv1 is provided via mpv package
https://launchpad.net/~mc3man/+archive/ubuntu/ffmpeg-test1

**Comment by godly-devotion** [comment]
@mc4man Thanks. We really appreciate it.

**Comment by laichiaheng** [comment]
Is there any difference between ppa:mc3man/trusty-media and ppa:mc3man/testing6
I have added ppa:mc3man/trusty-media in my repository.

**Comment by godly-devotion** [comment]
@mc4man Hey we just released our biggest update (2.0.3). We'd like to let Ubuntu 15.04 users be able to easily update via PPA method. Should I tell them to go to https://launchpad.net/~mc3man/+archive/ubuntu/ffmpeg-test1 as you said?

**Comment by mc4man** [comment]
sure - currently has baka 2.0.3 release, libmpv 0.9.2. ffmpeg is at 
2.6.2 & may get updated to 2.6.3 shortly.
As I don't spend much time on 15.04 any issues, concerns, what-not 
should be forwarded via LP email.
Doug

**Comment by godly-devotion** [comment]
@mc4man Thank you yet again.
