### ISSUE TITLE
change volume will change system volume, not app volume

### ISSUE THREAD

**Issue by Antares95** [u8sand/Baka-MPlayer#126]
OS:Linux, using pulseaudio.

**Comment by u8sand** [comment]
We're using MPV to adjust volume. MPV determines how with --softvol option,
when set to auto (the default) it's supposed to use app volume if available.

see if forcing softvol to yes fixes your issue:
(in settings)

    [mpv]
    softvol=yes

I'll check on my own system.

**Comment by Antares95** [comment]
softvol can solve the problem, thank you.
