### ISSUE TITLE
FreeBSD port link should be to FreshPorts, not svn repo

### ISSUE THREAD

**Issue by jbeich** [u8sand/Baka-MPlayer#129]
Arch/Gentoo/OpenSUSE link to package description page, not the underlying repository. Why FreeBSD is different? Can you replace the link with FreshPorts' one? The site is [recommended](https://www.freebsd.org/ports/searching.html) over primitive search on www.freebsd.org.

http://bakamplayer.u8sand.net/installation.php#linux
https://freshports.org/multimedia/baka-mplayer

If you look carefully FreshPorts also links to PortsMon where one can inspect availability of **binary** packages. Obsolete packages are rebuilt every few days. For one, baka-mplayer-2.0.3 missed the train just by 2 hours.

**Comment by godly-devotion** [comment]
Done! And thanks for taking time to manage the FreeBSD port! :smile:
