### ISSUE TITLE
fails to build with Converted settings to JSON

### ISSUE THREAD

**Issue by mc4man** [u8sand/Baka-MPlayer#130]
fail on ubuntu 14.04 only, 15.04 is ok
good build log cdce472     -    http://paste.ubuntu.com/11601287/
failed build log 9dbb167    -    http://paste.ubuntu.com/11601301/
(same fails seen on 2.0.3 release
Any ideas, outdated package in 14.04, ect?

**Comment by u8sand** [comment]
@mc4man Actually @godly-devotion had a similar issue. It looks to me like an outdated package--the error is simply that QJson objects don't have constructors with their default values, but clearly [they are supposed to](http://doc.qt.io/qt-5/qjsonvalue.html). And they do on my system. 
I'm using qt 5.4.2-1
Ubuntu seems to be ridiculously far behind. Qt doesn't leave much information about WHEN these changes occurred, but surely they should fix them selves with due time. I will proactively investigate this and figure out if there is some alternative--but getting around that seems at a glance--quite difficult.

**Comment by godly-devotion** [comment]
Tell 14.04 to upgrade lol

**Comment by mc4man** [comment]
I'll take a quick look but seems unlikely it's worth the hassle to produce new qtbase (5) package sets for 14.04 (or do an install  of the needed to /opt/  ect. workaround
(14.04 is on 5.2), so likely will just end 14.04 @ cde472

Note to any future affected 14.04 users - it's possible that one can do this locally/self builds, but not going to happen in a ppa unless there is an advanced qt5 ppa of  which I don't see any..

**Comment by LeeGing** [comment]
Debian testing with QT 5.3.2 has this problem too.QT 5.4.2 is still in experimental.It seems that i have to wait for it.
so I think the Requirements(qtbase5-dev (>= 5.2.0) ) should be changed to qtbase5-dev (>= 5.4.?) now.

**Comment by u8sand** [comment]
Please confirm for me that this fix works (not tried but it should work)

**Comment by mc4man** [comment]
Thanks for the try, while much improved still a couple of errors
http://paste.ubuntu.com/11628890/

**Comment by u8sand** [comment]
Thanks for the feedback--again I'll ask you to confirm if this did the trick.

**Comment by mc4man** [comment]
Ok - that's good to go
Thanks for the attention, as far as Ubuntu 15.04/15.10 will be ok as far as qt5, 16.04 should be well advanced also. Here I give only passing attention to these interim releases as they're only good for 9 months. 16.04 will get better as it is an lts (5 yr. support
