### ISSUE TITLE
[bug] toggling fullscreen removes playlist upon restore

### ISSUE THREAD

**Issue by Decme** [u8sand/Baka-MPlayer#133]
Bug - when playlist is shown on the right panel, double clicking the video for fullscreen playback, then double clicking again to restore to windowed mode hides the playlist (the playlist should be returned to its original position)

**Comment by u8sand** [comment]
I'm not sure I know what is SUPPOSED to be saved/not; could you outline this for me--then I can go about implementing it.

**Comment by godly-devotion** [comment]
Basically if playlist is shown and full screen is triggered, Baka MPlayer should remember whether or not the playlist was shown or not before going into full screen so that when the user leaves full screen it can show the playlist if it was shown before.

**Comment by u8sand** [comment]
Fixed in bffa23688795bdb341e73e1265db4394ba53cfc8
