### ISSUE TITLE
Playlist messes with PrntScr screenshots in fullscreen

### ISSUE THREAD

**Issue by starks** [u8sand/Baka-MPlayer#135]
When I PrntScr, I get this...

http://i.imgur.com/6aqxy46.jpg

Black pixels at the top and side.

Is there a way to completely disable the playlist or make its hover zone completely invisible? If anything, it should be the exact edge of the screen. Player controls exhibit a similar behavior and should simply be an overlay.

**Comment by u8sand** [comment]
The best way to take screenshots is with baka-mplayer's built-in screenshots as even if your window size is different than the actual video, you'll get the original resolution in the screenshot.

In terms of having the playlist not take space--this is a slight annoyance with the way Qt's Splitter works, I'll certainly look into it again in the future but it'll probably have to stay.

**Comment by TheAwesomeYankee** [comment]
For some reason, those black pixels appear all the time (i mean i don't even have to press prtscr)... I just watched video and noticed that there's some black space on the right side of the screen.
Am I the only one having this problem?

It happens the same on windows and linux.

**Comment by u8sand** [comment]
@TheAwesomeYankee That is correct, setting the splitter handle's width to 0 doesn't work, nor does hiding it (the entire area gets hidden)--because the body of the splitter is handled by the same class. I'll have to hack the widget to remove its visibility.
