### ISSUE TITLE
add ability to use youtube-dl's bestvideo+bestaudio format

### ISSUE THREAD

**Issue by Chaquator** [u8sand/Baka-MPlayer#136]
I've been trying to open 4K youtube vidoes in baka mplayer but they always end up at 720p, even when i add `"ytdl-format": "bestvideo+bestaudio"` (and yes i did put a comma at the end of the line before it)

could there be an option to specify what kind of format to use with ytdl, or, better yet, make it `bestvideo+bestaudio` by default? that'd require for you to make sure to alert the people downloading that theyd need ffmpeg installed (and in PATH on windows) if they were to.

**Comment by u8sand** [comment]
@Chaquator I've confirmed this, it would seem mpv is still only using "best" format, will investigate.
