### ISSUE TITLE
option to disable automatic playlist opening and scanning directory for video files

### ISSUE THREAD

**Issue by deathtrip** [u8sand/Baka-MPlayer#139]
it's annoying when you only wanna play one file, and takes resources to scan the directory

**Comment by ConundrumAdInfinitum** [comment]
Maybe as a selectable option. I actually find the default directory scan behavior useful.

**Comment by deathtrip** [comment]
as you can read in the title,a selectable option is exactly what i suggested

**Comment by godly-devotion** [comment]
Smart playlist was designed to be an integral part of Baka MPlayer. Therefore it was designed in a way to use resources as little as possible. You may have noticed we do not allow users to create their own playlists. Allowing automatic playlist to be disabled will make the playlist useless.

**Comment by Flat** [comment]
While this is marked as wontfix it'd be really nice to have an option to hide the playlist window on startup especially considering there's a UI button and a hotkey to open it. If not I suppose I can always just make my own fork.
