### ISSUE TITLE
Add Travis CI Support

### ISSUE THREAD

**Issue by godly-devotion** [u8sand/Baka-MPlayer#14]
Travis allows us to see if the current build successfully compiles or not. It also has a build history so we can see at what point exactly that the builds fails to compile.

http://docs.travis-ci.com

Edit: At the time of this writing, Travis is using Ubuntu 12.04 LTS, which does not have all the Qt5 files we need for it to compile successfully. For now, the files related to Travis has been moved to `etc/travis/`.

**Comment by u8sand** [comment]
I've taken some steps into getting this to work in the two branches: 
https://github.com/u8sand/Baka-MPlayer/tree/arch-travis
https://github.com/u8sand/Baka-MPlayer/tree/vanilla-travis

One step was adding our dependencies to the travis whitelist:
https://github.com/travis-ci/apt-package-whitelist/issues/2162
https://github.com/travis-ci/apt-package-whitelist/issues/2165
