### ISSUE TITLE
FEATURE REQUEST: Multiple Keymap Profiles

### ISSUE THREAD

**Issue by ConundrumAdInfinitum** [u8sand/Baka-MPlayer#140]
Hi Devs,

I think it would be really useful to incorporate Multiple Keymap Profiles for your Custom Keyboard Shortcuts into Baka-MPlayer.

Why?: Because if you are wanting to switch back and forth between the setup you have for say, your Numeric 10-Key Pad when you are using Windows and your full-size extended keyboard, and your Bluetooth Mini Keyboard with Touchpad; you would have to reprogram the Keymap Profile EACH time you want to switch devices.

A little sugar for making it easy to switch layouts/keymaps between multiple input devices would be sweet.

Currently (On Windows) the "bakamplayer.ini" file stores the keymap. Adding a button to the "Settings>Preferences>Keybindings" dialog would be welcome. You could name it "Keymaps" or "Profiles" and have a File Viewer dialog pop up to allow you to select from the *.ini file(s) you have modified and saved in the root folder of Baka-MPlayer.

I could also see a dedicated "Keymaps" or "Profiles" folder in the application's directory structure to house the different "insert-name-here-bakamplayer.ini" files for swapping keymaps kept in a tidy standard location.

P.S. I would like this feature very much and I don't see why your users wouldn't jump up and down for joy by having this modification added to Baka-MPlayer. 

Thanks for reading my Feature Request.

Also, when changing Key Assignments, it is REALLY EASY to hit RESET. Please consider rearranging the button layout on the Panel to make RESET harder to click.

Here is a screencap:
![image](https://cloud.githubusercontent.com/assets/8801348/9153692/d531b326-3e1d-11e5-99f7-62c23e48de43.png)

**Comment by u8sand** [comment]
I think this would be relatively simple to do, I could simply expand the
input section into a parent hash table called profiles:

"profiles": {
  "name": "your name",
  "input": {...}
}

unless you want fill configured profiles (not just input bindings but all
settings), then perhaps different settings files might make more sense.

**Comment by ConundrumAdInfinitum** [comment]
Question:

Wouldn't having multiple files to name/rename make backing up custom
keymaps easier and tidier??

**Comment by godly-devotion** [comment]
@ConundrumAdInfinitum No that violates the KISS principle, not to mention how messy that can get. I also don't really see the point of full profiles (not to mention that it goes against consistency).

**Comment by ConundrumAdInfinitum** [comment]
Hi Joshua,

I can see the point, esp. in relation to the KISS principle, of limiting
the keymap profile concept to a single file as Daniel pointed out.
