### ISSUE TITLE
Screenshots not working

### ISSUE THREAD

**Issue by VeralianIV** [u8sand/Baka-MPlayer#145]
By pressing ctrl+t,it says "says saved to ... ,with subs" but when going to that folder nothing is found.I tried changing the save folder to multiple location and drives but nothing worked.
when taking the screenshot,the message shows up almost immediately unlike in mpv where the player freezes for a while,shows the message and saves the screenshot to the designated folder.

**Comment by u8sand** [comment]
I'll look into this, I don't remember altering anything with screenshots
but I did alter settings-that may have done it.

**Comment by u8sand** [comment]
I've confirmed the presence of this bug, I'll figure out why it's here.

**Comment by u8sand** [comment]
Not sure if the transition works properly, but removing mpv/screenshot-{template,directory} from bakamplayer.ini will reset it and make it work.
