### ISSUE TITLE
FEATURE REQUEST: Option To Save Aspect Ratio "Force" Setting

### ISSUE THREAD

**Issue by csiegell** [u8sand/Baka-MPlayer#146]
There needs to be an option to save your Aspect Ratio "Force" setting ( Force 16:9, etc) as your preferred preference for all videos. Not to mention this is no hot key for this functionality, so it is cumbersome to enable constantly if your always watching the same videos. Additionally, it would be nice to be able to have a keyboard key as a switcher to switch between the different forced aspect ratios. Please implement.

**Comment by u8sand** [comment]
Please note that these settings are settable with the BakaEngine command and thus are assignable to your own keys.

Settings -> Preferences -> Key Bindings -> Add
`mpv set video-aspect -1`     for autodetect
`mpv set video-aspect 16:9`
`mpv set video-aspect 2.35:1`
`mpv set video-aspect 4:3`

(Even if it doesn't appear to show up properly, just click OK anyway it should work nonetheless, that's a bug we're in the process of fixing)

I hope this gives you the functionality you're looking for--if we care to add defaults, we will.

**Comment by godly-devotion** [comment]
As @u8sand has noted, you can add your own custom Key Bindings. I personally don't think having an option to save Aspect Ratio would be useful as every video's aspect ratio is different and can lead to annoyance later on.
