### ISSUE TITLE
FEATURE REQUEST: Video frame original/unscaled

### ISSUE THREAD

**Issue by VeralianIV** [u8sand/Baka-MPlayer#147]
Already [asked this](https://github.com/mpv-player/mpv/issues/1650) in mpv and found a solution but it's such a pain toggling it on/off every time when a video resolution is higher than my screen res.So is it possible to add that option in Baka player like it does in [kawaii codec pack](https://cloud.githubusercontent.com/assets/11322226/6516637/fea603b2-c369-11e4-9655-c3f2c0b41c7c.png)?It'll be very much appreciated.Thanks.

**Comment by godly-devotion** [comment]
@VeralianIV If Key Bindings was working correctly you would go to Settings -> Preferences -> Key Bindings -> Add. Enter what key combination you want this new option to have, then under Command, put `mpv cycle video-unscaled`, then press Add->Ok.

Right now it seems we have a major bug with Key Bindings that will need to be fixed.

@u8sand The Key Bindings page has some serious issues that need to be fixed (ie can't add new key bindings, Reset All clears all entries, etc)

**Comment by VeralianIV** [comment]
It worked !! thank you so much for this!!The days of changing the file name and restoring it are long gone.

**Comment by godly-devotion** [comment]
Glad it works.
