### ISSUE TITLE
some Chinese osd can't be fully showed

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#148]
![default](https://cloud.githubusercontent.com/assets/5022901/9320621/c2fafee2-458e-11e5-99ed-c37e100d0b77.PNG)
The characters in the picture mean "show subtitle", which are not fully showed. It seems to be the problem of font because this happens on ubuntu and windows but doesn't happen on linuxdeepin,a Chinese linux distribution.
I tried to add mpv configuration  ```"osd-font": "NotoSansHans"``` but nothing changed.

**Comment by u8sand** [comment]
Interesting--the width is based on Qt's FontMetrics class which is supposed
to tell me the width but it's had its issues in the past.

The best I can try is to add a margin of error to the overlay handler--is
it just the last character that's cut off or is there more?

**Comment by amazingfate** [comment]
just the last character

**Comment by u8sand** [comment]
@amazingfate please get back to me and tell me if that fixed it--QFontMetrics doesn't give me the right result so it really is just guess and check.
