### ISSUE TITLE
File association

### ISSUE THREAD

**Issue by mcjoeng** [u8sand/Baka-MPlayer#152]
Why not associate baka-mplayer with multimedia files

**Comment by u8sand** [comment]
If you're referring to unloading file associations into your registry; I'm
more interested in the portable approach where we leave your system alone
as much as possible--is it not easy enough to "open as"?

**Comment by godly-devotion** [comment]
Also Windows 10 makes it really hard for programs to assign themselves.

**Comment by ConundrumAdInfinitum** [comment]
I agree with the current approach. FYI, I'm on Windows 10, and I found it
easy enough to both "Open With..." and to associate with a SPECIFIC File
Format, but not as a "Handler" for a Protocol, nor as a "Default" app.

Browse to a video file, Right-Click, select Open With, Scroll down to, then
Click on "More Apps" (in the Context-Sensiive Menu), then Click on "Look
for another app on this PC", and Browse to the applications *.exe file in
File Explorer.

Then you will have that particular File Format associated with Baka.

You have to do this for each File Format.

A helper function to associate formats with Baka might be "nice", now that
I think about it...

The problem on Windows 10 is that the Settings menus for changing File
Associations do not ALL have the option of browsing to the Program
Location...

**Comment by mcjoeng** [comment]
on linux desktop

**Comment by amazingfate** [comment]
Which desktop environment do you use? As I know all popular desktop environments support file association.

**Comment by BlackIC** [comment]
For Windows - I've modified the script from https://github.com/rossy/mpv-install for Baka MPlayer.

http://pastebin.com/iPkUw6FM

Place it in the directory where Baka MPlayer.exe resides and it should do the trick.

All credits belong to the original author - I've just changed a few pathes and modified the arguments so it works with Baka MPlayer. 

While I understand that you do not like to include it by default - maybe you could add it to the repo and give a hint for the windows users and that the credits go to rossy.

Cheers!

**Comment by u8sand** [comment]
Thank you for your contribution, we'll find a place for this and we can use
it as reference in the future if we decide to make adding associations
easier.

**Comment by vith** [comment]
`baka-mplayer.desktop` should also have a `MimeType` entry so that Baka MPlayer will appear in "Recommended Applications" when choosing "Open With Other Application" on Gnome for example.

https://github.com/mpv-player/mpv/blob/v0.16.0/etc/mpv.desktop#L30

**Comment by u8sand** [comment]
Fixed in #210
