### ISSUE TITLE
Config file not being created on OSX

### ISSUE THREAD

**Issue by Illya** [u8sand/Baka-MPlayer#153]
The config file which should be in ~/.config/bakamplayer.ini is not being created, OSX normally handles config files a little differently to linux in that it should use ~/library/Application Support/Baka-MPlayer/config.ini (for example)

**Comment by u8sand** [comment]
We use QStandardsPath which according to [this](http://doc.qt.io/qt-5/qstandardpaths.html) it should be that location, but no Baka-MPlayer/config.ini-- baka-mplayer.ini; could this be the issue?

**Comment by Illya** [comment]
After doing a `find`, I found that it was infact in ~/Library/Preferences/bakamplayer.ini, so it is saving, but not following the standard of reverse domain, and PList format, this should be ok. 
An improvement would be to use ~/library/Application Support/Baka-MPlayer/config.ini but, at the moment it works. However, I see no particular reason to have to change it.
