### ISSUE TITLE
have an option to not store history of receantly played videos.

### ISSUE THREAD

**Issue by mhogomchungu** [u8sand/Baka-MPlayer#163]
using baka player 2.0.3.

There are privacy concerns with storing the info and it would be nice if there was an option to not do it.

**Comment by u8sand** [comment]
Set maxRecent option to 0 in settings to disable the feature.

**Comment by mhogomchungu** [comment]
I see no such option,where is it supposed to be?

**Comment by u8sand** [comment]
In the settings file, located in ~/.config/bakamplayer.ini  on Linux or
with the exe on windows.

**Comment by godly-devotion** [comment]
I'll add an option under Preferences.
