### ISSUE TITLE
[Feature request] Automatically add external audio

### ISSUE THREAD

**Issue by Mirenkorax** [u8sand/Baka-MPlayer#166]
I have a file that comes with external .mka audio, and I can't load it through the front-end. This is my first ever issue report on here, I just made an account, sincere apologies if I should not have done this or wasted anybody's time.

**Comment by u8sand** [comment]
@Mirenkorax can you just confirm that this works for me, I don't really have a .mka lying around to test it--it should work because it's very similar to subtitles.

**Comment by Mirenkorax** [comment]
Adding external audio works. It dosen't recognize .mka files though, so I had to extract the AC3 audio from it to test it.

**Comment by u8sand** [comment]
@Mirenkorax ahh, I'll add mka to the list

    {"*.mp3","*.ogg","*.wav","*.wma","*.m4a","*.aac","*.ac3","*.ape","*.flac","*.ra", "*.mka"}

any others missing?
