### ISSUE TITLE
Subititles Squished Together

### ISSUE THREAD

**Issue by chair96** [u8sand/Baka-MPlayer#173]
I'm getting this issue where the subtitles on top are squished completely together. Making the font size smaller sorta fixes this but then the bottom subtitles are extremely small. Wondering if anyone knows how to fix this without messing up the bottom subtitles. http://imgur.com/JiYxOAo

**Comment by u8sand** [comment]
Interesting... I believe mpvs font size property is for all fonts, this seems like weird libass use-case. I'll see if this is something we can fix here, else we'll direct it towards mpv.

**Comment by chair96** [comment]
Alright thanks. I just tested the same file on the windows version and the subtitles worked completely fine but on arch linux they are completely squished for some reason

**Comment by u8sand** [comment]
That's funny because i develop this on arch and don't use windows. Might it be related to a missing font?

**Comment by chair96** [comment]
I guess so, I am getting the same issue with multiple different players. Is there a package I can install that would have the right font?

**Comment by u8sand** [comment]
Noting the following link: https://mpv.io/manual/master/#options-osd-font
What may be happening is that they didn't specify a font and so the default sans-serif font is being used. The Window's version uses Noto Sans, to emulate this on the linux version after installing `noto-fonts`, in `~/.config/bakamplayer.ini` add...

    ...
    "mpv": {
        ...
        "osd-font": "Noto Sans"
    },
    ...

This will make the default osd font noto sans, subtitles that don't specify their font will then use this.

**Comment by chair96** [comment]
Is this correct?http://imgur.com/LCWYFiG

I installed noto-fonts and added the line to the bakamplayer.ini but the problem persists.

This is what the command line says when I play the OP:

[mpv]: Playing: /mnt/media1/Torrents/Kateikyoushi Hitman Reborn (DVD 576p) (Kyuu9Jango)/(Hi10)_Kateikyoushi_Hitman_Reborn_-_OP01_(DVD_576p)_(Kyuu9Jango)_(9EB96F11).mkv
[mpv]:  (+) Video --vid=1 (*) (h264)
[mpv]:  (+) Audio --aid=1 (*) (aac)
[mpv]:  (+) Subs  --sid=1 (*) (ass)
[mpv]: AO: [pulse] 48000Hz stereo 2ch float
[mpv]: VO: [opengl] 768x576 yuv420p10
[mpv]: Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
[mpv]: fontselect: Using default font family: (MV Boli, 700, 0) -> /usr/share/fonts/TTF/DejaVuSans-Bold.ttf, 0, (none)
[mpv]: fontselect: Using default font family: (Tahoma, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, (none)

**Comment by u8sand** [comment]
Your config looks good.

I wonder why it ignored the font entirely and went for DejaVuSans--still that tells us that the subs are looking for MV Boli and Tahoma both of which are being replaced by DejaVuSans so we may be on the right track.

maybe try `sub-text-font` instead of `osd-font` in the config.

**Comment by chair96** [comment]
Ok so I changed it to sub-text-font int he config:http://imgur.com/m5uIFXv

However, it still looks like this:http://imgur.com/Ln0lX5w

The command line does say it's using the noto fonts though.

[mpv]: Playing: /mnt/media1/Torrents/Kateikyoushi Hitman Reborn (DVD 576p) (Kyuu9Jango)/(Hi10)_Kateikyoushi_Hitman_Reborn_-_OP01_(DVD_576p)_(Kyuu9Jango)_(9EB96F11).mkv
[mpv]:  (+) Video --vid=1 (*) (h264)
[mpv]:  (+) Audio --aid=1 (*) (aac)
[mpv]:  (+) Subs  --sid=1 (*) (ass)
[mpv]: AO: [pulse] 48000Hz stereo 2ch float
[mpv]: VO: [opengl] 768x576 yuv420p10
[mpv]: Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
[mpv]: fontselect: Using default font family: (MV Boli, 700, 0) -> /usr/share/fonts/TTF/NotoSans-Bold.ttf, 0, (none)
[mpv]: fontselect: Using default font family: (Tahoma, 400, 0) -> /usr/share/fonts/TTF/NotoSans-Regular.ttf, 0, (none)

This is what it looks like on the windows version:http://imgur.com/BNz4rv7

**Comment by blackarcher21** [comment]
yes, I also guess it might be related to a missing font. I guess you need to install additional fonts (for example. ttf-ms-win10 from AUR)

**Comment by u8sand** [comment]
As long as you have those two fonts `Tahoma` and `MV Boli` you should get the intended effect by the subber. Most subtitles come with the fonts embedded (in the mkv), i suppose this one expected you to have the font. I would expect blackarcher21's suggestion to work.

**Comment by chair96** [comment]
I downloaded the two fonts and now it displays correctly. Thanks for all the help u8sand and blackarcher21 :)
