### ISSUE TITLE
Not really issues, rather questions.

### ISSUE THREAD

**Issue by dragons4life** [u8sand/Baka-MPlayer#174]
How can I add sharpening? with a mpv.conf?
What do motion interpolation and deinterlance do?

Anyway you can make it so that on fullscreen whenever you hover over the seekbar/volume and stuff it doesn't change the aspect ratio? (basically make it on be on top of the video) this would be a request, but it's fine if other users like the way it is, is not that annoying.

**Comment by u8sand** [comment]
mpv configurations can be added in json form to the .ini. (I'm considering adding accessibility to this in the gui #167)

If you already have an mpv config it's easy
`key=value` -> `"key": "value"`  in bakamplayer.ini in `"mpv": {...}`

From mpv's manual,
You can sharpen it w/ software with: `sws-ls` or `sws-cs` [-100 to 100]: eg. `"sws-ls": 50`
You can sharpen it w/ your vo driver (assuming opengl): `"vo": "opengl:sharpen=1"`
For more information, please consult mpv's manual.

**Comment by dragons4life** [comment]
thanks

**Comment by u8sand** [comment]
We'll talk about your second question in #226
