### ISSUE TITLE
piping output

### ISSUE THREAD

**Issue by klick4karma** [u8sand/Baka-MPlayer#182]
i have a script that marks the stdout of songs i like when using mpv.  baka seems to trap stdout and writes a blank file. 
suggestions?

**Comment by u8sand** [comment]
@klick4karma I'm not sure I'm aware of this mpv feature, what are you hoping to get from stdout, the song itself? or some mpv output?

**Comment by klick4karma** [comment]
im using " | tee -a mpv.log"  . to log streaming radio titles etc. works
fine when calling mpv.

baka, not so much.

**Comment by u8sand** [comment]
@klick4karma I see, can you confirm that in the debugging console `Ctrl + \`` [default] the titles appear as you expect them to?

**Comment by klick4karma** [comment]
im not at the computer, but the title s  do appear in the window bar...yes

**Comment by u8sand** [comment]
@klick4karma Ok, it should be relatively easy to print mpv's output to stdout, I'll set that up--may even help with general debugging.

**Comment by klick4karma** [comment]
thank you sir.

ill bug you about  mpv profiles another day
