### ISSUE TITLE
[Feature Request] Please add logging and command line arguments

### ISSUE THREAD

**Issue by MissingNoIOI** [u8sand/Baka-MPlayer#187]
When you currently use Baka Mplayer on Linux there are apparently neither logging capabilities nor command line arguments save for the filename. At least for me it would be very useful if Baka Mplayer would give me any kind of informations on error, if it cant play a file right now it simply skips it and I have no idea why it does that. Is a codec missing? Is the file corrupt? It would be very helpful if the program would write an error to STDERR. Maybe one could implement that with a coomand line flag like -v.

 That brings me to my second request. As far as I can see Baka Mplayer doesn't write anything to STDOUT and doesn't have any command line arguments. Again, I would find it helpful if the program allowed me to set some settings from the command line for this session only, but that's not as important for me as error messages.

**Comment by u8sand** [comment]
We've recently made Baka MPlayer output the same messages appearing in the debugging console to stdout (#184). If that information isn't verbose enough, please set the debugging level in the preferences dialog.

Though I've considered building a command-line system, I've yet to see a strong reason to do so, as a primarily graphical-based application it would feel redundant to have command line options for all of the options you can use with configuration.

**Comment by wb9688** [comment]
I think it's very useful, for example when you always want to play music
from a folder, you can make an shortcut for it and even Firefox has
commandline options...
Op 10 jan. 2016 15:49 schreef "Daniel Clarke" <notifications@github.com>:

**Comment by u8sand** [comment]
@wb9688 as you can open a directory with baka-mplayer you can already do that, what would the command-line flags be trying to do?

**Comment by wb9688** [comment]
@u8sand Open the directory on startup.
And when we have commandline arguments, we can use the open with feature of our file manager...

**Comment by u8sand** [comment]
Not sure I was clear--the current state of baka-mplayer's "command-line-arguments" is as follows:

`baka-mplayer [file-or-directory]`

eg. `baka-mplayer myfile.mkv` or `baka-mplayer .`

**Comment by wb9688** [comment]
Oh, didn't know that...
Op 10 jan. 2016 16:09 schreef "Daniel Clarke" <notifications@github.com>:
