### ISSUE TITLE
Not really an issue, but which one is the 64 bit of the releases?

### ISSUE THREAD

**Issue by dragons4life** [u8sand/Baka-MPlayer#191]
Kinda confuse..

Also have being trying to merge my mpv.conf with your player the only changes I am putting softvol=yes
softvol-max=300
--sws-ls=50
I put them on the "mpv" folder, but it doesn't work guessing I can't change settings of the player via a conf file?

I also tried doing it trough the bakamplayer.ini file in json, but it deletes the text added after reopening the player.

**Comment by u8sand** [comment]
@dragons4life make sure the player isn't running when you modify the config. Then run it and when you close it your settings should have been saved. (It loads settings on startup and saves them on close)

it would go under `mpv`: `"mpv": { "softvol-max": 300, ... }` But I've played around with softvol myself and  it have never worked for me (in baka or mpv). It also doesn't seem like the mpv project is interested in fixing it as "mpv is a video player, not an audio mixer."

**Comment by dragons4life** [comment]
ahh it's fine thanks @u8sand
