### ISSUE TITLE
Playing audio without embedded album art causes player to crash

### ISSUE THREAD

**Issue by Chromace** [u8sand/Baka-MPlayer#192]
The attached zip contains two audio files with only one difference between them: one has embedded album art (via a music tagger). Opening the one without the album art in Baka-MPlayer causes it to crash. Opening it in mpv causes no problems - it plays with a blank screen.

[Sample Music.zip](https://github.com/u8sand/Baka-MPlayer/files/109432/Sample.Music.zip)

**Comment by godly-devotion** [comment]
The one **without** the album art causes it to crash? That's very odd. Also what OS are you using?

**Comment by Chromace** [comment]
I am using Arch Linux.

**Comment by u8sand** [comment]
@Chromace It interestingly doesn't crash on my system (I also use ArchLinux). Regardless the culprit is most likely our overlay handler. Overlay handler uses mpv's add-overlay system to overlay the video through mpv. It's really messy and a bad way to do it but it was the only way at the time; now we can obtain an opengl device context from mpv and overlay it in a normal way.

This is part of an ongoing refactoring project that has slowed down significantly recently due to my workload outside of this project.

**Comment by Chromace** [comment]
@u8sand Thanks. I know a little more now (always good).

Why might Baka be fine playing audio with album art, but not without?

**Comment by u8sand** [comment]
Largely has to do with the overlayhandler.  When there is album art, we write to a virtual image and then we pass that image on to mpv to display it, later on we take it out and delete the image (all very messy).  When there is no album art, mpv doesn't do any displaying whatsoever, so we create our own image then we overlay it. If mpv reports that there is an image when their isn't it might crash, or if it said there wasn't an image when their is it might crash.

**Comment by u8sand** [comment]
As mentioned a few other issues, the best way to debug baka is getting its own outputted debugging information (put on stdout). You'd have to compile from master--(as you're on archlinux this would be from AUR: `baka-mplayer-git`).

**Comment by Chromace** [comment]
@u8sand Using the master build, Baka MPlayer appears to be playing audio without embedded album art fine. Instead of crashing, a placeholder image is displayed. In fact, the regular community repository version of Baka also handles this audio fine, displaying the same placeholder image.

![without album art](https://cloud.githubusercontent.com/assets/16624211/13876118/0559cdee-ed56-11e5-9cf0-c6b27a4b8628.png)

I wonder what happened...?

**Comment by u8sand** [comment]
@Chromace Yes, it is indeed strange. Someone else is having the issue https://github.com/u8sand/Baka-MPlayer/issues/200 though. We've tried a lot of things to little avail. I'll close this issue, any further developments can be mentioned in the other issue.

I'm glad it's working for you :+1:
