### ISSUE TITLE
Segfault in libmpv with some mp3 files

### ISSUE THREAD

**Issue by aelog** [u8sand/Baka-MPlayer#193]
I'm on Archlinux, baka v2.0.4 and mpv v0.15.0.

In the attached files you can find the backtrace from the coredump and the valgrind log.
The crash seems to be in libmpv, so I installed debug symbols only for mpv. If you need debug symbols also for baka, let me know and I will install them.

[baka-backtrace.txt](https://github.com/u8sand/Baka-MPlayer/files/109593/baka-backtrace.txt)
[baka-valgrind.txt](https://github.com/u8sand/Baka-MPlayer/files/109594/baka-valgrind.txt)

**Comment by Chromace** [comment]
Did those files have any embedded album art in them?

**Comment by aelog** [comment]
@Chromace Nope. They are mp3 encoded (with lame) out of .wav voice recordings

**Comment by Chromace** [comment]
This is just a guess, but does playing them with embedded album art work properly? It might be related to my issue.

**Comment by aelog** [comment]
@Chromace Can you suggest me an app to do so? I'm not familiar with mp3 embedding :)

**Comment by Chromace** [comment]
Kid3. That's what I use.

**Comment by aelog** [comment]
@Chromace You're right! After embedding a picture in the mp3, Baka does not crash anymore!

**Comment by Chromace** [comment]
Looks like it's similar to my issue. ( #192)

**Comment by Chromace** [comment]
I'm going out on a limb but...do the audio files (without album art) make Baka crash, but work fine in mpv?

**Comment by aelog** [comment]
@Chromace 
Yes, they can be played with mpv just fine.

**Comment by godly-devotion** [comment]
@aelog @Chromace After reading both your issues I believe it is the same issue as #181. This will hopefully be fixed when we switch over from mpv overlay based code to drawing text ourselves via QML.

**Comment by Chromace** [comment]
@godly-devotion What will mpv be responsible for after that?

**Comment by godly-devotion** [comment]
@Chromace mpv is still our main playback engine. We were using mpv's overlay system to show status and album art but that is currently causing issues so we will handle that part ourselves.

**Comment by Chromace** [comment]
@godly-devotion This might be a silly question after that, but does that mean mpv will still be responsible for displaying subtitles? Thanks.

**Comment by godly-devotion** [comment]
@Chromace Yes. Subtitles and overlay code are different.

**Comment by u8sand** [comment]
We'll just merge these two issues with #192
