### ISSUE TITLE
With 320 kbps .mp3's, it shows they're 320000 kbps

### ISSUE THREAD

**Issue by wb9688** [u8sand/Baka-MPlayer#198]
When I play a 320 kbps .mp3, Baka-MPlayer shows it's a 320000 kbps .mp3:

![](http://i.imgur.com/cy3RMQC.png)

**Comment by u8sand** [comment]
Looks like mpv is reporting it in bps instead of kbps for that file. And it almost seems like it's always been like that i'll fix it.
