### ISSUE TITLE
proxy for player

### ISSUE THREAD

**Issue by Love4Taylor** [u8sand/Baka-MPlayer#199]
need proxy for youtube

**Comment by u8sand** [comment]
@Love4Taylor I'm not sure I understand what it is you're looking for, could you please elaborate?

Youtube support is provided by youtube-dl, if you're asking to be able to pass the `--proxy` flag, add the following to your `bakamplayer.ini` in the `mpv` section:

    "ytdl-raw-options": "proxy=your_proxy"

**Comment by prahulkgp** [comment]
I apologize if I should not be asking this question here but how do I force the player to check for updates through proxy? Thank you.

**Comment by Love4Taylor** [comment]
I use socks5 but don‘t work
`"ytdl-raw-options": "proxy=socks5://127.0.0.1:1080/"`
![](https://ws1.sinaimg.cn/large/005GmrUUgw1fblkco0cv9j30g704bt9g.jpg)
![](https://ws3.sinaimg.cn/large/005GmrUUgw1fblkdrjohdj30lz04440h.jpg)

**Comment by u8sand** [comment]
As a workaround, you can probably use proxychains or another related
utility. Those work for all applications.
