### ISSUE TITLE
Tray Icon Does Nothing?

### ISSUE THREAD

**Issue by Geyup** [u8sand/Baka-MPlayer#211]
Hello,

I compiled 2.0.4 from source, below are my system specs;

Slackware 14.1 x86_64
Openbox 3.6.1
tint2 0.12.11
QT5 5.5.1

When I enable the system tray icon it appears in the tint2 system tray section, but when I click on it, it does nothing. Left & Right clicks nothing, can't minimize to tray, not sure what capability this tray icon has. Maybe it's still in development, or just not working well with tint2 in Openbox?

**Comment by chinese-soup** [comment]
It should toggle play/pause if you have a file loaded (even if playback is stopped using Ctrl-S it should start playing back a file), did you try it with a file opened?

**Comment by Geyup** [comment]
Sorry I stopped using this, just using mpv by itself...
