### ISSUE TITLE
Baka-Mplayer doesn't show image after Qt5 update

### ISSUE THREAD

**Issue by GrandGamer** [u8sand/Baka-MPlayer#221]
After upgrading my system to Qt 5.7 and setting things up to look ok, I run into [this problem](http://i.imgur.com/FHtsWqe.png). After deleting Baka-Mplayer.ini file in ~/.config the color changed to [this](http://i.imgur.com/5n6CGOb.png). I even tried uninstalling and reinstalling but to no avail.

Audio works fine, default mpv works fine. VLC also seems to work fine.

**EDIT**: This happens only when Qt5 Style is set to "gtk2" through qt5ct.

I'm on Manjaro XFCE with Compiz and Emerald decorator.

Any ideas?

**Comment by u8sand** [comment]
Very strange, I believe I'm on qt 5.7 as well but I'm not experiencing
this. Was baka recompiled after the update? Sometimes that has implications.

**Comment by GrandGamer** [comment]
It wasn't and as I mentioned in my original post edit, it only occurs with [gtk2 style in qt5ct](http://i.imgur.com/CmBXyuU.png).

**Comment by xsmile** [comment]
Same issue here with Arch Linux and baka-mplayer 2.0.4-2.

Exporting `QT_QPA_PLATFORMTHEME=qt5ct` and setting `gtk2` in the Qt5 Configuration Tool qt5ct seems to be the cause.

I noticed that the video is visible if hardware acceleration via vaapi is disabled or if vdpau is used instead.

**Comment by GrandGamer** [comment]
This doesn't seem to be working for me or I'm doing something wrong. How do you choose to use vdpau on Baka-Mplayer?

**Comment by xsmile** [comment]
@GrandGamer:

See https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Installing_VA-API for details. Also install `libvdpau-va-gl` as the backend for vaapi.

Afterwards you have to edit the file `~/.config/bakamplayer.ini` and set the hwdec and vo options:
```
    "mpv": {
        "hwdec": "vdpau",
        [...]
        "vo": "vdpau",
    },
```

**Comment by GrandGamer** [comment]
That worked like a charm, thank you!
