### ISSUE TITLE
Windows MCE Remote stopped working in Ubuntu 16.10

### ISSUE THREAD

**Issue by amalv** [u8sand/Baka-MPlayer#232]
I've just upgraded Ubuntu from version 16.04 to version 16.10

In Ubuntu 16.04 the remote buttons worked fine and I could assign them to commands through Settings > Preferences > Key bindings.

However after upgrading to Ubuntu 16.10 this has stopped working and the remote no longer works with Baka Mplayer.

I know the remote still works fine since I've installed lirc in order to test it and the remote commands showed fine in the terminal screen.

Any suggestions?

**Comment by u8sand** [comment]
If you try to specify the key input and press the button on the remote does
it register in the keyboard input box? If Baka will register them for
assignment it should work, while the name of the key code may have changed.

**Comment by amalv** [comment]
Unfortunately it does not register in the input box (in Ubuntu 16.04 it did and showed the name in the Shortcut box)

![shortcutkey](https://cloud.githubusercontent.com/assets/1252707/20456416/a8378484-ae76-11e6-9038-d56e200c8736.png)

Also out of the box in Ubuntu 16.04 (before configuring any shortcut), the play button was associated with the play_pause command and it worked fine.

**Comment by u8sand** [comment]
Does this fix work? http://askubuntu.com/questions/787257/media-keys-not-passing-after-upgrade-to-16-04/811454

**Comment by amalv** [comment]
The fix is for the Microsoft keyboard and not the remote I think. The remote is like this:

![mceremote](https://cloud.githubusercontent.com/assets/1252707/20456565/4aaf28c8-ae79-11e6-9732-f5215e744150.jpg)

Nonetheless I've checked if I had the `joystick` package installed (I did not have it installed), and if there was a file named '51-these-are-not-joysticks-rm.rules' (there wasn't).

I've also checked the `77-mm-usb-device-blacklist.rules` file but there was nothing suspicious there neither.

**Comment by u8sand** [comment]
I see, primarily my concern was that your MediaKeys aren't being registered and we simply use Qt5's key input functionality.  Perhaps it's related to this seemingly unresolved bug, also in a qt5 program, https://bugs.launchpad.net/ubuntu/+source/texmaker/+bug/1386111

>After purging appmenu-qt5 my shortcuts (terminal shortcut and media keys as well) were working again.

**Comment by amalv** [comment]
Thanks for the input, I will try to search info about Qt5 input functionality and fix this.

I've also noticed that the remote in Ubuntu 16.04 also controlled the OS volume and now that is also not working.

So this is not really a problem related to Baka Mplayer, it seems like a general problem, so I think this issue can be closed. Thanks anyways!
