### ISSUE TITLE
Not displayed correctly under Fedora25

### ISSUE THREAD

**Issue by tautcony** [u8sand/Baka-MPlayer#233]
After I upgraded the system to Fedora25, open a video with baka-mplayer will full-screen display the video at behind which I can not control its size and show a player without image, the playlist/controls work well ont the player.

If I select full-screen in the player, the empty player will cover the image, I've tried to rebuild the player but it still not work correctly.

![baka-mplayer under fedora25](https://cloud.githubusercontent.com/assets/8295052/20637996/47f85f48-b35e-11e6-8468-376dca39ee49.png)

**Comment by godly-devotion** [comment]
Fedora 25 switched their windowing system from Xorg to Wayland. That is most likely what is causing the issue.

@u8sand I wonder if mpv's Wayland support is ready.

**Comment by u8sand** [comment]
Perhaps it's our Wayland support that isn't ready. We may need to call mpv
differently for Wayland (usually we pass a window id to mpv).

I'll install Wayland and investigate this.

**Comment by u8sand** [comment]
This is a part of Wayland Support #188
