### ISSUE TITLE
mpv 0.23.0 support

### ISSUE THREAD

**Issue by SEAPUNK** [u8sand/Baka-MPlayer#239]
I'm not sure if baka-mplayer fully supports mpv 0.23.0, because when I upgraded to that version, various things like the seek bar and the "total time" segment of the time elapsed stopped working.

**Comment by SEAPUNK** [comment]
Thank you!

**Comment by u8sand** [comment]
No problem; thanks for reporting it. I've neglected to pay attention to mpv's depreciation notices so a few properties were renamed in the recent versions without me knowing.
