### ISSUE TITLE
Seeking Issue

### ISSUE THREAD

**Issue by sirx** [u8sand/Baka-MPlayer#242]
I can't seek anymore through the video and I'm on Arch Linux.

I seriously don't know what's the deal with this but I have version 2.0.4

Anyone else experiencing the same?

**Comment by u8sand** [comment]
This is because mpv has upgraded but Baka hasn't had any major releases.
We're working on one, in the meantime please use baka-mplayer-git

**Comment by sirx** [comment]
Thanks! :3
