### ISSUE TITLE
Missing <math.h> include in src/ui/mainwindow.cpp

### ISSUE THREAD

**Issue by snorkellingcactus** [u8sand/Baka-MPlayer#249]
Hi.
  Build fail for me on linux because of ceil beign used on src/ui/mainwindow.cpp.
  If i add <math.h> at the end of the includes it compiles and works fine.
Thanks you.

**Comment by u8sand** [comment]
This issue sounds like #169 I wonder why the old fix didn't work on your system (using QtMath & qCeil)
