### ISSUE TITLE
Audio playback occasionally very quiet

### ISSUE THREAD

**Issue by SEAPUNK** [u8sand/Baka-MPlayer#257]
For some strange reason, while switching the currently playing video in a playlist or just starting up baka-mplayer to play a video, the playback volume is _very_ quiet, even at 100% volume. Closing and restarting the player a few times seems to fix it; it happens seemingly randomly.

Running off of the latest commit on master.

```
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May  8 20:03:32 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.1
```

**Comment by u8sand** [comment]
This might be a mpv bug, can you confirm that it doesn't occur on mpv itself?

**Comment by SEAPUNK** [comment]
It's been a while, but I don't think it was an mpv problem. I think the issue can be closed for now, since I won't be able to repro anymore, and it's been a while ago.
