### ISSUE TITLE
:-1: error: mpv development package not found

### ISSUE THREAD

**Issue by jx5261zy** [u8sand/Baka-MPlayer#264]

**Comment by jx5261zy** [comment]
:-1: error: mpv development package not found

**Comment by u8sand** [comment]
I'm sorry but I'm going to need a bit more context.

What operating system, what output this error, how was it installed?

Sincerely,
Daniel J. B. Clarke

**Comment by FateRover** [comment]
ok,though maybe  this project do not continue ,here some info which i have the same issue:

>  Logged from file Logs.py, line 162
> Checking for waf version in 1.8.4-2.1.0  : ok 
> Checking for program 'cc'                : /usr/bin/cc 
> Checking for program 'pkg-config'        : /usr/bin/pkg-config 
> Checking for program 'ar'                : /usr/bin/ar 
> Checking for program 'rst2html'          : /usr/bin/rst2html 
> Checking for program 'rst2man'           : /usr/bin/rst2man 
> Checking for program 'rst2pdf'           : not found 
> Checking for program 'windres'           : not found 
> Checking for program 'perl'              : /usr/bin/perl 
> Checking for 'gcc' (C compiler)          : /usr/bin/cc 
> Detected target OS:                      : os-linux 
> Checking for compiler flags -Werror=implicit-function-declaration : yes 
> Checking for compiler flags -Wno-error=deprecated-declarations    : yes 
> Checking for compiler flags -Wno-error=unused-function            : yes 
> Checking for compiler flags -Wempty-body                          : yes 
> Checking for compiler flags -Wdisabled-optimization               : yes 
> Checking for compiler flags -Wstrict-prototypes                   : yes 
> Checking for compiler flags -Wno-format-zero-length               : yes 
> Checking for compiler flags -Werror=format-security               : yes 
> Checking for compiler flags -Wno-redundant-decls                  : yes 
> Checking for compiler flags -Wvla                                 : yes 
> Checking for LGPL (version 2.1 or later) build                    : disabled 
> Checking for GPL (version 2 or later) build                       : yes 
> Checking for internal audio filter chain                          : yes 
> Checking for mpv CLI player                                       : yes 
> Checking for shared library                                       : yes 
> Checking for static library                                       : disabled 
> Checking for static build                                         : disabled 
> Checking for whether to include binary compile time               : yes 
> Checking for whether to optimize                                  : yes 
> Checking for whether to compile-in debugging information          : yes 
> Checking for manpage generation                                   : yes 
> Checking for html manual generation                               : disabled 
> Checking for pdf manual generation                                : disabled 
> Checking for dynamic loader                                       : yes 
> Checking for C plugins                                            : yes 
> Checking for zsh completion                                       : yes 
> Checking for inline assembly (currently without effect)           : yes 
> Checking for test suite (using cmocka)                            : disabled 
> Checking for generate a clang compilation database                : disabled 
> Checking for compiler support for noexecstack                     : yes 
> Checking for linker support for --nxcompat --no-seh --dynamicbase : no 
> Checking for -lm                                                  : yes 
> Checking for MinGW                                                : os-win32 not found 
> Checking for POSIX environment                                    : yes 
> Checking for Android environment                                  : no 
> Checking for Android EGL support                                  : android not found 
> Checking for development environment                              : yes 
> Checking for Universal Windows Platform                           : disabled 
> Checking for win32 desktop APIs                                   : os-win32 not found 
> Checking for internal pthread wrapper for win32 (Vista+)          : posix found 
> Checking for POSIX threads                                        : yes 
> Checking for GNU C extensions                                     : yes 
> Checking for stdatomic.h                                          : yes 
> Checking for stdatomic.h support or slow emulation                : yes 
> Checking for linking with -lrt                                    : yes 
> Checking for iconv                                                : yes 
> Checking for w32/dos paths                                        : os-win32 not found 
> Checking for spawnp()/kill() POSIX support                        : yes 
> Checking for spawnp()/kill() Android replacement                  : posix-spawn-native found 
> Checking for any spawnp()/kill() support                          : yes 
> Checking for Windows pipe support                                 : posix found 
> Checking for glob() POSIX support                                 : yes 
> Checking for glob() win32 replacement                             : posix found 
> Checking for any glob() support                                   : yes 
> Checking for fchmod()                                             : yes 
> Checking for vt.h                                                 : yes 
> Checking for gbm.h                                                : yes 
> Checking for GLIBC API for setting thread name                    : yes 
> Checking for OSX API for setting thread name                      : glibc-thread-name found 
> Checking for BSD API for setting thread name                      : glibc-thread-name found 
> Checking for BSD's fstatfs()                                      : no 
> Checking for Linux's fstatfs()                                    : yes 
> Checking for Samba support (makes mpv GPLv3)                      : yes 
> Checking for Lua                                                  : yes (version found: 52arch) 
> Checking for Javascript (MuJS backend)                            : no ('mujs >= 1.0.0' not found) 
> Checking for SSA/ASS support                                      : yes 
> Checking for libass OSD support                                   : yes 
> Checking for dummy OSD support                                    : libass-osd found 
> Checking for zlib                                                 : yes 
> Checking for Bluray support                                       : yes 
> Checking for dvdread support                                      : yes 
> Checking for dvdnav support                                       : yes 
> Checking for DVD/IFO support                                      : yes 
> Checking for cdda support (libcdio)                               : yes 
> Checking for uchardet support                                     : yes 
> Checking for librubberband support                                : yes 
> Checking for LCMS2 support                                        : yes 
> Checking for VapourSynth filter bridge (Python)                   : no ('vapoursynth >= 24 vapoursynth-script >= 23' not found) 
> Checking for VapourSynth filter bridge (Lazy Lua)                 : no ('vapoursynth >= 24' not found) 
> Checking for VapourSynth filter bridge (core)                     : vapoursynth not found 
> Checking for libarchive wrapper for reading zip files and more    : no ('libarchive >= 3.0.0' not found) 
> Checking for SDL2                                                 : disabled 
> Checking for OSS                                                  : yes 
> Checking for RSound audio output                                  : no 
> Checking for sndio audio input/output                             : disabled 
> Checking for PulseAudio audio output                              : yes 
> Checking for JACK audio output                                    : yes 
> Checking for OpenAL audio output                                  : yes 
> Checking for OpenSL ES audio output                               : no 
> Checking for ALSA audio output                                    : yes 
> Checking for CoreAudio audio output                               : no 
> Checking for AudioUnit output for iOS                             : no 
> Checking for WASAPI audio output                                  : os-win32 not found 
> Checking for Cocoa                                                : no 
> Checking for DRM                                                  : yes 
> Checking for DRM Prime ffmpeg support                             : no 
> Checking for GBM                                                  : yes 
> Checking for wayland-scanner                                      : yes 
> Checking for wayland-protocols                                    : no ('wayland-protocols >= 1.14' not found) 
> Checking for Wayland                                              : wayland-protocols not found 
> Checking for X11                                                  : yes 
> Checking for Xv video output                                      : yes 
> Checking for OpenGL Cocoa Backend                                 : cocoa not found 
> Checking for OpenGL X11 Backend                                   : yes 
> Checking for OpenGL X11 EGL Backend                               : yes 
> Checking for OpenGL DRM EGL Backend                               : yes 
> Checking for OpenGL Wayland Backend                               : wayland not found 
> Checking for OpenGL Win32 Backend                                 : win32-desktop not found 
> Checking for OpenGL/DirectX Interop Backend                       : gl-win32 not found 
> Checking for OpenGL ANGLE headers                                 : os-win32 not found 
> Checking for OpenGL Win32 ANGLE Library                           : egl-angle not found 
> Checking for OpenGL Win32 ANGLE Backend                           : egl-angle not found 
> Checking for VDPAU acceleration                                   : yes 
> Checking for VDPAU with OpenGL/X11                                : yes 
> Checking for VAAPI acceleration                                   : yes 
> Checking for VAAPI (X11 support)                                  : yes 
> Checking for VAAPI (Wayland support)                              : gl-wayland not found 
> Checking for VAAPI (DRM/EGL support)                              : yes 
> Checking for VAAPI GLX                                            : yes 
> Checking for VAAPI EGL on X11                                     : yes 
> Checking for VAAPI EGL                                            : yes 
> Checking for CACA                                                 : yes 
> Checking for JPEG support                                         : yes 
> Checking for Direct3D support                                     : win32-desktop not found 
> Checking for libshaderc SPIR-V compiler (shared library)          : no 
> Checking for libshaderc SPIR-V compiler (static library)          : no 
> Checking for libshaderc SPIR-V compiler                           : shaderc-shared not found 
> Checking for libcrossc SPIR-V translator                          : no ('crossc' not found) 
> Checking for Direct3D 11 video output                             : win32-desktop not found 
> Checking for Raspberry Pi support                                 : no 
> Checking for iOS OpenGL ES hardware decoding interop support      : no 
> Checking for OpenGL without platform-specific code (e.g. for libmpv) : yes 
> Checking for MALI via Linux fbdev                                    : no 
> Checking for OpenGL context support                                  : yes 
> Checking for Vulkan context support                                  : no ('vulkan' not found) 
> Checking for EGL helper functions                                    : yes 
> Checking for FFmpeg/Libav present                                    : yes 
> Checking for libav* is FFmpeg                                        : no 
> Checking for libav* is Libav                                         : no 
> Checking for Libav/FFmpeg library versions                           : ffmpeg not found 
> Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
> **make[1]: *** [debian/rules:64：override_dh_auto_configure] 错误 1
> make[1]: 离开目录“/home/pad/下载/Baka-MPlayer/build/mpv-build”
> make: *** [debian/rules:23：build] 错误 2
> dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2**
> ****dpkg: 错误: 无法访问归档 '../mpv*.deb': 没有那个文件或目录**
> 正克隆到 'Baka-MPlayer'...**
> remote: Counting objects: 8661, done.
> remote: Total 8661 (delta 0), reused 0 (delta 0), pack-reused 8660
> 接收对象中: 100% (8661/8661), 4.26 MiB | 1.76 MiB/s, 完成.
> 处理 delta 中: 100% (6464/6464), 完成.
> **Info: creating stash file /home/pad/下载/Baka-MPlayer/build/Baka-MPlayer/.qmake.stash
> lupdate: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lupdate': No such file or directory
> lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease': No such file or directory
> Project ERROR: mpv development package not found**
> **make: *** 没有指明目标并且找不到 makefile。 停止。
> make: *** 没有规则可制作目标“install”。 停止。**

 here some trans of chinese in the info(maybe not exactly,but i think u can understand it),i have make main error info bold

    错误  =  error
    错误: 无法访问归档 '../mpv*.deb': 没有那个文件或目录  =  can not accsess file ../mpv no such file or folder
    正克隆到  =  clonning
    没有指明目标并且找不到  = canot find

**Comment by u8sand** [comment]
Your error output says `Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.` `FFmpeg`/`Libav` is required for `mpv` to compile, and `mpv` is required for `baka-mplayer` to compile. Therefore if you install the necessary dependencies for `mpv` first, the rest will successfully install.

I do not maintain the files needed to install baka-mplayer, I only write the source code which can be compiled given that all necessary dependencies are available as described on the README.

**Comment by vejeta** [comment]
@jx5261zy For the error:
> -1 error: mpv development package not found

If you are in Debian GNU/Linux, install it with:
`sudo apt-get install libmpv-dev `
Otherwise use the package manager of your operating system

@FateRover:
for the ffmpeg/libav development libraries, you probably need one of those:
Doing a search, I find.
`apt-cache search ffmpeg|grep libav|grep dev                                                `

> ibavcodec-dev - FFmpeg library with de/encoders for audio/video codecs - development files
> libavdevice-dev - FFmpeg library for handling input and output devices - development files
> libavdevice57 - FFmpeg library for handling input and output devices - runtime files
> libavfilter-dev - FFmpeg library containing media filters - development files
> libavformat-dev - FFmpeg library with (de)muxers for multimedia containers - development files
> libavresample-dev - FFmpeg compatibility library for resampling - development files
> libavutil-dev - FFmpeg library with functions for simplifying programming - development files

**Comment by GAO-sw** [comment]
> 

you save me ,thx

**Comment by GAO-sw** [comment]
> @jx5261zy For the error:
> 
> > -1 error: mpv development package not found
> 
> If you are in Debian GNU/Linux, install it with: `sudo apt-get install libmpv-dev ` Otherwise use the package manager of your operating system
> 
> @FateRover: for the ffmpeg/libav development libraries, you probably need one of those: Doing a search, I find. `apt-cache search ffmpeg|grep libav|grep dev `
> 
> > ibavcodec-dev - FFmpeg library with de/encoders for audio/video codecs - development files
> > libavdevice-dev - FFmpeg library for handling input and output devices - development files
> > libavdevice57 - FFmpeg library for handling input and output devices - runtime files
> > libavfilter-dev - FFmpeg library containing media filters - development files
> > libavformat-dev - FFmpeg library with (de)muxers for multimedia containers - development files
> > libavresample-dev - FFmpeg compatibility library for resampling - development files
> > libavutil-dev - FFmpeg library with functions for simplifying programming - development files

you save me , thx
