### ISSUE TITLE
How to use hardware decoding

### ISSUE THREAD

**Issue by wzhy90** [u8sand/Baka-MPlayer#266]
I cant find any hardware decoding settings in menu and the command line is always showed "VO: opengl" event if I create a mpv profile in ~/.config/mpv/mpv.config.

**Comment by u8sand** [comment]
That's because baka-mplayer does not take mpv.config into account. Please add your settings to bakamplayer's settings https://github.com/u8sand/Baka-MPlayer/blob/master/DOCS/settings.md
