### ISSUE TITLE
Add automatic subtitle detection

### ISSUE THREAD

**Issue by Smile4ever** [u8sand/Baka-MPlayer#267]
At least ".srt", ".*.srt" (for example, a file ending with .en.srt) in the current directory and the subdirectory "subs".

First asked in #186

**Comment by u8sand** [comment]
Both `.srt` and `.sub` are considered in general application flow. Relevant filetypes here:
https://github.com/u8sand/Baka-MPlayer/blob/master/src/mpvtypes.h#L16

Frankly I was under the impression mpv automatically detected these types of files itself, hence the code we have here to ask about deleting sub files with the same name but different extension:
https://github.com/u8sand/Baka-MPlayer/blob/master/src/widgets/playlistwidget.cpp#L281-L317

In fact the related issue in mpv is: https://github.com/mpv-player/mpv/issues/4008  which suggests that adding `sub-auto=fuzzy` to config would help. You can add this to baka-config yourself but I'll add it as one of the default parameters.

**Comment by u8sand** [comment]
Mpv has a setting for this, I don't plan to add it as a default setting because I don't think people usually anticipate this functionality.

```

       --sub-file-paths=<path-list>
              Specify extra directories to search for subtitles matching the video.  Multiple directories can be separated by ":" (";" on  Windows).
              Paths  can be relative or absolute. Relative paths are interpreted relative to video file directory.  If the file is a URL, only abso‐
              lute paths and sub configuration subdirectory will be scanned.

                 Example

                        Assuming that /path/to/video/video.avi is played and --sub-file-paths=sub:subtitles is specified, mpv searches for  subtitle
                        files in these directories:

                 · /path/to/video/

                 · /path/to/video/sub/

                 · /path/to/video/subtitles/

                 · the sub configuration subdirectory (usually ~/.config/mpv/sub/)

              This is a list option. See List Options for details.

```
To add it, add it to the mpv options in bakamplayer.ini
