### ISSUE TITLE
The progress bar won't work.

### ISSUE THREAD

**Issue by jay763190097** [u8sand/Baka-MPlayer#269]

**Comment by bless-9** [comment]
use the git version this one works the baka-mplayer doesn't work correctly.(baka-mplayer-git 2.0.4-1)


baka-mplayer-git

**Comment by u8sand** [comment]
Related to #265 . I'm not sure why it doesn't work for you, can you please share which versions of libmpv you are using to compile baka-mplayer-git? It seems to work on my fully up to date system, and perhaps run it in terminal and provide any relevant error messages.

![untitled](https://user-images.githubusercontent.com/1341861/41202182-5b7451ea-6c93-11e8-84f9-3fd3002dba3f.png)

**Comment by jay763190097** [comment]
I didn't compile baka-mplayer-git, just used the release version.

**Comment by u8sand** [comment]
Use baka-mplayer-git from the AUR, not the release version.

**Comment by jay763190097** [comment]
@u8sand It fix after useing baka-mplayer-git , hope you can release a new version.

**Comment by jay763190097** [comment]
It would be be even better if the title bar and menu bar could be hidden.

**Comment by jay763190097** [comment]
@u8sand It would be be even better if the title bar and menu bar could be hidden.
