### ISSUE TITLE
Turkish Lang

### ISSUE THREAD

**Issue by oltulu** [u8sand/Baka-MPlayer#271]
baka-mplayer_tr.ts was added but not compiled. There is no baka-mplayer_tr.qm.
![resim](https://user-images.githubusercontent.com/3286652/41202299-a508d4d4-6ccf-11e8-94bb-e316a4f61001.png)

**Comment by u8sand** [comment]
@oltulu A bug was introduced not too long ago that I experienced while merging your changes, the `ru` translation has a bug in it causing all languages not to compile. As a temporary fix, you can remove the the _ru.ts file from the directory to properly build all the translation. I'll be fixing it shortly however.
