### ISSUE TITLE
ruan baka-mplayer error

### ISSUE THREAD

**Issue by oOTnTOo** [u8sand/Baka-MPlayer#273]
error while  loading shard libraries: libmpv.so.1: connot open shard object file: No such file or directory.
but ,I am build and install mpv-build , and the libmpv.so.1 in /usr/local/lib/ now. why?

**Comment by u8sand** [comment]
You can try `ldd baka-mplayer | grep mpv` to see where it is (or isn't) that baka-mplayer is looking for `libmpv.so.1`
