### ISSUE TITLE
The installation link for Ubuntu doesn't work.

### ISSUE THREAD

**Issue by toto6038** [u8sand/Baka-MPlayer#287]
The URL provided on [http://bakamplayer.u8sand.net/installation.php](http://bakamplayer.u8sand.net/installation.php) for [Ubuntu(Launchpad)](https://launchpad.net/~mc3man/+archive/ubuntu/ffmpeg-test1) seems not exist.

**Comment by mc4man** [comment]
I got rid of that ppa a long time ago
If you want for 18.04, https://launchpad.net/~mc3man/+archive/ubuntu/bionic-media
For 16.04 
https://launchpad.net/~mc3man/+archive/ubuntu/xerus-media

Note that hwdec for nvidia is possible for these build via vdpau, if I update libmpv that will not be possible (or hard..
baka should add support for nvdec but don't see that happening as this project appears pretty much dead...
