### ISSUE TITLE
volume stuck in specific range while `volume up` and `volume down`

### ISSUE THREAD

**Issue by Kienyew** [u8sand/Baka-MPlayer#293]
when I wanted to volume up or volume down the video's audio (command is `volume +5` and `volume -5`, final volume will only increased or decreased to a specific small range (as in the gif below, 52% to 62%). But dragging the volume scrollbar below works finely.

![Peek 2020-05-23 11-04](https://user-images.githubusercontent.com/31496021/82720379-99343200-9ce5-11ea-811c-92cebea68136.gif)

**Comment by Kienyew** [comment]
later I found that `volume +5` and `volume -5` is just always be an offset from a specific value, instead of relative to that current volume, in case above, offset from 57% (resulting 52% and 62%).

**Comment by u8sand** [comment]
@Kienyew this is what makes it relative https://github.com/u8sand/Baka-MPlayer/blob/master/src/bakacommands.cpp#L545-L546

In my tests it looks like mpv somehow reverted things so that `volume` and `mute` work properly again...  I'll revert 10dd37212fc685e9eecf1819601c8d951f587c77  and commit it if it works.

**Comment by Kienyew** [comment]
Thanks for viewing this issue, just recompiled and tested just now.
The problem seems resolved. :+1:

**Comment by u8sand** [comment]
Believe it or not I still use this player myself even though I don't have much time to keep it maintained.. If it's easy i'll fix it, some more elaborate requests I'm deferring..

**Comment by Kienyew** [comment]
I was also struggled to find a video player in linux that fits my habits for a long time and find out this is a nice one, simple, pretty, yet greatly functionable. Still looking forward on the development of this project :)
