### ISSUE TITLE
Baka MPlayer: Replace header image

### ISSUE THREAD

**Issue by godly-devotion** [u8sand/Baka-MPlayer#298]
I don't think Baka MPlayer is actually hosted in this repo but I couldn't find the source.

Since we aren't going to create a macOS version of Baka MPlayer, I think we should replace the main screenshot with something like this instead: ![](https://u8sand.github.io/Baka-MPlayer/screenshots/img-1.png)

This is already hosted on the server so it should be as easy as changing the img tag on the main page.

Also might as well delete the macOS preview image lol.

**Comment by u8sand** [comment]
It's actually here https://github.com/u8sand/Baka-MPlayer/tree/master/website -- i'll change the image later :+1:

**Comment by godly-devotion** [comment]
Fixed via f09db332194463e56ea72612c595bbe76360523f

**Comment by u8sand** [comment]
Cheers -- gotta love github actions :tada:

**Comment by godly-devotion** [comment]
Yup. How far this project has come. Quite unfortunate that I still haven't been able to find a good looking media player for Windows but I use Mac now so 🤷‍♂️
