### ISSUE TITLE
Not only short seek/jump but also long?

### ISSUE THREAD

**Issue by slrslr** [u8sand/Baka-MPlayer#309]
VLC & MPV player has short and medium jump/seek during video playback (medium jump is up/down key, Baka player 2.0.4 use these keys for playlist jump ATM) the time i have is 30 seconds.
Celluloid & Gnome Mplayer has 60 seconds long jump

It may be good if Baka player also support long jump/seeking,

Current short seek time is 10 seconds (i think most players use the same)

EDIT: i see i can manually create it in Preferences (command: mpv seek +30), somehow it was not apparent to me for the first time, may be good to pre-create it so is there by default for new user.

**Comment by u8sand** [comment]
@slrslr it is the default. It's likely that you had the playlist selected/open when you used the up/down arrows. If you hide the playlist or click on the video the playlist should no longer capture the keypress and it should trigger the seek.

**Comment by slrslr** [comment]
i tried to rename ~/.config/bakamplayer.ini and launch the BakaMPlayer , the settigs was reset and i have tried to long jump in the video using Up,Down keys, it does not work. When i enable playlist and add some files, then these keys highligh previous/next entry in the playlist. so im my case there is not and longer jump/seek by default like it is in other players, as mentioned in my first post.

**Comment by u8sand** [comment]
I stand corrected; I've had this set in my preferences for so long I forgot. I think this is a good suggestion.
