### ISSUE TITLE
how to rotate video

### ISSUE THREAD

**Issue by standin000** [u8sand/Baka-MPlayer#310]
I can not find a menu item or hotkey to rotate video in baka-mplayer, Is there possible?

**Comment by u8sand** [comment]
@standin000

You can rotate the video using mpv commands, the command to cycle 90 degree intervals will be:
```
mpv cycle_values video-rotate 0 90 180 270
```

So you can create a key binding:
![image](https://user-images.githubusercontent.com/1341861/129490074-a7b68227-6540-40c9-a035-95bd4cda2b33.png)

Once added, you can press r (in this case, but use whatever shortcut you want) to rotate the video.
