### ISSUE TITLE
Left click to pause/play, drag to move window/gesture

### ISSUE THREAD

**Issue by Yasand123** [u8sand/Baka-MPlayer#328]
First of all, I want to thank the dev/s for this amazing media player. I feel like I finally found the perfect (or near perfect) player on Linux after trying out so many options. It is very clear that so much love and care went into developing it, tiny details most people would overlook but make all the difference were taken care of here, with usability and polish in mind. Sane default shortcuts (for the most part), the seekbar doesn't show up in fullscreen unless you actually hover the pointer over it. It disappears immediately upon leaving the area... it's perfection.

Now, I still have a couple of suggestions/ideas, and this is one of them.

I find the current behavior of left/right mouse button a _little_ annoying because it's not consistent in full-screen vs windowed. Is it not possible to assign left mouse click to play/pause on clicking, and move the window (or gestures if enabled) on click+drag? Maybe add a 10 pixel window, where if the mouse moved while the left mouse button is being held for the distance of 10 pixels, it would trigger window movement/gesture controls, otherwise it would register as a click.

There's another solution, assuming the first suggestion is impossible, which is to change what the left mouse button does depending on the mode. If fullscree, it pauses/plays, if windowed, it moves the window (assuming gestures are not being used). Because currently LMB is useless in fullscreen, given that I don't use gestures.

And if even that is not possible, then I'd really like an option to only assign pause/play to left mouse button and completely disable drag & gestures altogether. As moving the window isn't a priority and can be done with the Super key.

**Comment by u8sand** [comment]
@Yasand123 thank you for your kind words. We tried our best but unfortunately the other *imperfection* with this media player is that it's somewhat neglected by its maintainer (me) :cry: .

In any-case your proposed change doesn't sound too difficult to add. Since existing users will be familiar with right click to play/pause, I'm decided to just add an option "Left click Play/Pause"

![image](https://user-images.githubusercontent.com/1341861/211212642-8dbe0429-5688-4de1-90b4-04fa403f5aa7.png)

I believe it behaves the way you expect, please let me know. You can test it it's in the `left-click-play-pause` branch.

**Comment by Yasand123** [comment]
@u8sand yes, building on windows in general is more tedious sadly, but I think it's a really solid product so neglecting it completely would be a real shame. I think it's worth checking out from time to time, doesn't have to be under constant development.

I just compiled it after the update, and this is exactly what I wanted, I can pause/play AND move the window as well. Thank you! One little thing though, since this functionality is mapped to the left mouse button, I think the context menu should be enabled outside of full screen on right mouse click. Currently it doesn't do anything. But it's not a big deal, so don't feel the need to fix it now. Take your time.

Again, thank you for the hasty reply and commit :)! Have a great day/night sir.

**Comment by u8sand** [comment]
I've addressed the context menu concern and merged it. Thanks again for the feedback.

**Comment by Yasand123** [comment]
Awesome :)
