### ISSUE TITLE
Usability Enhancement Request: Active Edge for Playlist while in Fullscreen Mode

### ISSUE THREAD

**Issue by ConundrumAdInfinitum** [u8sand/Baka-MPlayer#58]
Hello,

I think the new Stable Release for Windows is very nice, Thank You!

I would like to make an Enhancement Request.

I think it makes sense for the UI to have an Active Edge for the Playlist on the Right Hand Edge to be Dynamic while the App is in Fullscreen Mode just like the Bottom Edge is Dynamic with regard to the mouse/cursor hovering to the edge of the screen to show/hide (expose) the UI Elements.

In the case of the Bottom Edge it was the Filer Button, Timeline, Play Control Buttons, and Playlist Button, all handy, to have dynamically slide in and out of view while in Fullscreen mode. 

I'm making the case that the same thing goes for the Playlist while clicked Active, and the App is then placed in Fullscreen Mode. I think it would be desirable to have Fullscreen Mode be TRULY Fullscreen, and have the UI Elements pertaining to the Playlist on the Right Hand Side dynamically slide in and out of view via a Dynamic Edge triggered by the mouse/cursor.

**Comment by u8sand** [comment]
If you want settings for both please request in another issue.
