### ISSUE TITLE
can't play files in the root directory of a disk on windows

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#60]
I rebooted to windows today and found that baka-mplayer started with a cmd window.
When I opened a file in the root directory of a disk like E:\\[106].rmvb, nothing happened. If I move it into a directory under E it will be played well.
![default](https://cloud.githubusercontent.com/assets/5022901/5592149/853c019a-91f3-11e4-8e17-93aa6530510c.PNG)

**Comment by u8sand** [comment]
Yeah the command window is a nuisance which should solve itself in due time.

I don't have much of a clue as to WHY this is happening; I will have to setup a dev environment on windows to debug. In the meantime--could you open the developer debugging console then try and open the file (which doesn't open) and post the output here. But I think I disabled the debugging messages on the release version; I'll compile a new version and get it to you.

**Comment by ConundrumAdInfinitum** [comment]
Where is the developer debugging console?

**Comment by ConundrumAdInfinitum** [comment]
I'm on Windows... Wondered if I could help...
