### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by luigino** [u8sand/Baka-MPlayer#63]
For some reason the strings in the playlist pop-up menu (e.g. "Delete from Disk") aren't translated even if linguist says otherwise.

Also the "open file" requester isn't either, but perhaps that's another issue?

**Comment by u8sand** [comment]
I'm pretty sure this is a result of my dynamic translations; I'll look into fixing it.

**Comment by u8sand** [comment]
> Also the "open file" requester isn't either, but perhaps that's another issue?

I'm not entirely sure what you're referring to here.

**Comment by amazingfate** [comment]
Maybe this window
![48](https://cloud.githubusercontent.com/assets/5022901/5594175/27d09250-927a-11e4-9fba-8f85572a3aaf.png)

**Comment by u8sand** [comment]
@amazingfate O.o I see; that window is generated by Qt so that's strange. I'll look into it

**Comment by u8sand** [comment]
You may note: https://github.com/u8sand/Baka-MPlayer/blob/master/src/ui/mainwindow.cpp#L78-L84 
This is seemingly the solution (http://stackoverflow.com/questions/8906944/qfiledialog-localization).

However it doesn't work on my system, trying to figure out why not (as I do have qt translations in my /usr/share/qt/translations directory.

**Comment by amazingfate** [comment]
The Chinese translation from qt can't be loaded but other language can be loaded. I found the Chinese translation file is /usr/share/qt5/translations/qt_zh_CN.qm. Maybe this is the problem?

**Comment by luigino** [comment]
> The Chinese translation from qt can't be loaded but other language can be loaded. I found the Chinese translation file is /usr/share/qt5/translations/qt_zh_CN.qm. Maybe this is the problem?

I see that is the case also for other apps. I suppose the distinction is necessary to differentiate between Mandarin/Cantonese and simplified/traditional.

Although every locale supports that, in theory.

**Comment by u8sand** [comment]
Oh! So this is why @amazingfate made that change.

**Comment by u8sand** [comment]
From what I understand this is also solved with the latest changes.
