### ISSUE TITLE
can not increase sub size with ctrl++

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#82]
but I can decrease it with ctrl+-

**Comment by u8sand** [comment]
@amazingfate I can just fine. Perhaps look in your settings file and make sure there is no entry masquerading it in [input]

**Comment by amazingfate** [comment]
it should be the problem of mpv
the output of mpv:
```
[input] No bind found for key 'Ctrl+='.
```
I should input "ctrl + shift + =" because in my the board = and + are the same key
