### ISSUE TITLE
advise to build windows release using MSYS2

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#84]
Stuck in the issue of console window for a long time, I tried to change mxe to MSYS2, which is a tool under windows. I've built a version of baka-mplayer with dynamic link libraries, which is opened without console window. It seems to be the problem of qt5 built in mxe. MSYS2 uses pacman to manage the packages and we can just use command ```pacman -S qt5-static``` to install the static qt5. Other packages are also easy to install. One of the most advantages of MSYS2 is that it is a system under windows, which can build mpv with dxva2-copy(maybe dxva in the future) support. The one built with mxe can not use dxva2-copy now.
Now there are still building issues with MSYS2:
* 1, I can not still build static libmpv, maybe I have to build all the static versions of the dependeces of mpv.
* 2, embeded translations doesn't work. Although I added  ```CONFIG+=embed_translations``` but the exe came without any translations.

Scripts can be found here: https://github.com/amazingfate/baka-build

**Comment by u8sand** [comment]
Yes, you have to build all static dependencies when building statically.  The problem might be that your msys doesn't have qt linguist  (lupdate / lrelease commands).  You may also notice that lupdate and lrelease are specified on ./configure in the bakamplayer.sh script.

**Comment by amazingfate** [comment]
@u8sand I knew why the translations didn't work:
command  ```echo \'<RCC><qresource prefix=\"/\">\' > translations.qrc``` got the error: ```bash: syntax error near unexpected token `<'```
then it shows system can not find file

**Comment by u8sand** [comment]
I can't imagine why but anyway you can probably just comment the line out and keep the current translations.qrc  (though you won't be able to automagically select which translations, it'll just be all)

**Comment by amazingfate** [comment]
I tried that but seemed not working. The errors disappeared but still came out with no translations.
Full log is here: http://paste.ubuntu.com/9794644/

**Comment by u8sand** [comment]
the issue seems to be BAKA_MPLAYER_LANG_PATH. The compile line says
something about unrecognized \m where nothing of the sort should be there.
perhaps you need to add a define into the source code  for embedded the
path is:

:/translations

**Comment by amazingfate** [comment]
BAKA_MPLAYER_LANG_PATH isdefined later in the .pro file
```
DEFINES += "BAKA_MPLAYER_VERSION=\\\"$$VERSION\\\"" \
           "SETTINGS_FILE=\\\"$$SETTINGS_FILE\\\""
           "BAKA_MPLAYER_LANG_PATH=\\\"$$BAKA_LANG_PATH\\\""
```
there is something wrong with ```\\\"$$BAKA_LANG_PATH\\\""```

**Comment by u8sand** [comment]
Indeed--but only on your platform. If i change it to work on your platform it most likely will not work on mine.  To mitigate this I recommend having a source file where you define things..

    system("cat > defines.h << EOF
    #define BAKA_MPLAYER_VERSION $$VERSION
    #define SETTINGS_FILE $$SETTINGS_FILE
    #define BAKA_MPLAYER_LANG_PATH $$BAKA_LANG_PATH
    EOF")
    
    #include "defines.h" // in necessary files (eg. preferences.cpp)

**Comment by amazingfate** [comment]
my mistake, I should use ```mingw32-make``` to build it, and now the translations are back.
but now I can't build it with the last commit: http://paste.ubuntu.com/9801754/

**Comment by u8sand** [comment]
@amazingfate preferencesdialog was changed but I haven't gotten to coding it. will-do in a bit.

**Comment by u8sand** [comment]
By the way, does this also solve #88? That-is can we see mpv overlay text produced by `mpv shot_text "Test"`?

**Comment by amazingfate** [comment]
@u8sand .srt subtitle files also don't work

**Comment by amazingfate** [comment]
got an issue: showtext works if the .exe is in the build directory but doesn't work in other directories.
even .ass subtitles don't show up.

**Comment by amazingfate** [comment]
I found that when showtext works fine, a cache file in C:\Users\liujianfeng\AppData\Local\fontconfig\cache is used by baka-mplayer.exe or mpv.exe.

**Comment by amazingfate** [comment]
ahhhhhhh~ finally fix it!
just as http://lists.freedesktop.org/archives/fontconfig/2007-October/002685.html said: 
```The DLL should be in "someprefix\bin" (or "someprefix\lib", although
that is not really recommended), and the fonts.conf file then in
"someprefix\etc\fonts". If the DLL is in a folder whose last component
isn't "bin" or "lib", then the fonts.conf file should be in
"etc\fonts" directly under that folder.```
but it will take a long time to cache fonts for the first time of running

**Comment by godly-devotion** [comment]
@amazingfate btw if the problem with building statically is due to dxva2 and libbluray, that's still pretty good. dxva output on mpv uses copyback which isn't that great imo and although people may be using blu ray images, it's still pretty rare.

**Comment by amazingfate** [comment]
@godly-devotion now it got new issues, not only libbluray, there is also something wrong with libzip and  static qt5. I'm trying to fix them.

**Comment by u8sand** [comment]
As mxe fixed itself w/ the windows console--I'm thinking of sticking with it. What other things were mxe builds missing?

**Comment by amazingfate** [comment]
some deps of mpv can not be built staticly, but it seems not a big issue
