### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by muzena** [u8sand/Baka-MPlayer#91]
When I start video file, Baka-Mplayer is crash and in terminal I get Segmentation fault message.
I have Linux Mint 17.1 64 bit.

**Comment by u8sand** [comment]
@muzena We'll have to narrow your problem down a little better.
A few things to try:
- does the video work with just mpv? what is your mpv version?
- could you provide the output of `ldd baka-mplayer`

**Comment by muzena** [comment]
mpv works in Smplayer.
I have mpv from these repositories:
https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media
https://launchpad.net/~mc3man/+archive/ubuntu/libmpv1
ldd baka-mplayer output:
http://pastie.org/9877198

**Comment by u8sand** [comment]
@muzena I see.. unfortunately this didn't narrow it down as well as I wanted. You seem to have all the necessary dependencies and nothing really seems to be out of date.

Let's try `strace -o trace baka-mplayer`; try to play a video (inducing the segfault). Then put the output as a pastie. (in the file trace)

**Comment by muzena** [comment]
Baka-Mplayer starts normally, then when I select video file I get segmentation fault message in terminal:

mint@linux ~ $ strace -o trace baka-mplayer
Segmentation fault
mint@linux ~ $

**Comment by u8sand** [comment]
Correct; now the file `trace` has the output you should put on pastie.

**Comment by muzena** [comment]
trace file is to big for pastie.
MEGA link:
https://mega.co.nz/#!TplG3Lwb!xzaXGadGVgUVJ0px3hGijAzyDan8sGt-5G9nnV0uJAM

**Comment by u8sand** [comment]
@muzena because diagnosing the problem has proved futile. I decided to obtain Linux Mint system myself. I've successfully built a working version of baka-mplayer, soon I will provide you with the relevant package, hopefully solving your issues.

**Comment by muzena** [comment]
OK, thanks!

**Comment by u8sand** [comment]
@muzena btw if you're interested in compiling it yourself, my scripts should prove useful for you.

https://github.com/u8sand/Baka-MPlayer/tree/master/etc/sbin/linux

I'll get you a compiled .deb this weekend. Do you use a 32 or 64 bit OS?

**Comment by godly-devotion** [comment]
Compiling should now work with https://github.com/u8sand/Baka-MPlayer/blob/master/etc/sbin/linux/debian_based.sh

**Comment by u8sand** [comment]
@muzena Sorry this took so long to get. Been busy lately.
You'll find a working libmpv below:
https://dl.dropboxusercontent.com/u/13483445/mpv_0.7.3_amd64.deb

After installing that deb package, compile and install baka and everything should work properly.
