### ISSUE TITLE
build ffmpeg with --enable-dxva2 in mxe

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#93]
The ffmpeg mxe provided is not configured with dxva2 support, but in MSYS2 there is ```--enable-dxva2``` parameter: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-ffmpeg/PKGBUILD. Maybe this is why the one built by mxe doesn't support dxva2 hardware acceleration.
I can't build mxe now because of my poor network. We can have a try.

**Comment by u8sand** [comment]
@amazingfate I've compiled successfully with the new flag, i'll have to ask @godly-devotion to test it for me.

One of our biggest concerns at the moment with Windows compilation is fontconfig. With the correct fonts.conf file fonts shouldn't need to be cached (which takes a long time and makes it seem like the program is frozen initially and any time fonts change).

lach0r's mpv build doesn't have this issue, we must use his example to do the same. Whether with mxe or msys2 I don't care that much, just want something that works.

**Comment by amazingfate** [comment]
Yeah fontconfig is a big problem, I've compiled fontconfig with patches lachs0r provides in msys2 but it still caches fonts for a long time, only change is that it can support fonts in directory /fonts and fonts.conf in /mpv which is provided by mpv, I'm considering to recompile all the dependence of mpv to see what will happen.

**Comment by godly-devotion** [comment]
@amazingfate then technically speaking, can't we use the `fonts.conf` file that lachs0r uses for his windows build to stop fontconfig from caching?

**Comment by amazingfate** [comment]
@godly-devotion it should can but now only fonts.conf works, it stiil cached fonts in /c/Windows/Fonts.
mpv lachs0r builds also caches fonts but it uses fonts in /font directory so it takes a very short time

**Comment by amazingfate** [comment]
@godly-devotion wow it works! We should copy /font and /mpv folder mpv provides and replace ```/etc/fonts/fonts.conf```

**Comment by godly-devotion** [comment]
@amazingfate great! the next step is to get static compilation working now

**Comment by u8sand** [comment]
I've confirmed that this works well. I'll soon be putting more effort into the pursuit of msys2 as our build system. Thank you for your continued effort towards this cause @amazingfate

**Comment by u8sand** [comment]
This was enabled in my build scripts (which I should put in the repo--I will soon).
