### ISSUE TITLE
can't show all file type in file dialog

### ISSUE THREAD

**Issue by amazingfate** [u8sand/Baka-MPlayer#94]
file dialog doesn't contain all file type that baka--mplayer can play, we can just add a choose of all file type

**Comment by u8sand** [comment]
@amazingfate the only issue with this is it won't behave well with the playlist. The playlist doesn't load files with unrecognized extensions. Perhaps we need to extend that list?
I can also look into letting the user choose "any type" and add that specific type to this list.
I'll probably get to this tomorrow evening. Please list here any more types that don't exist.

Here is the type list:

    const QStringList audio_filetypes = {"*.mp3","*.ogg","*.wav","*.wma","*.m4a","*.aac","*.ac3","*.ape","*.flac","*.ra"},
                      video_filetypes = {"*.avi","*.divx","*.mpg","*.mpeg","*.m1v","*.m2v","*.mpv","*.dv","*.3gp","*.mov","*.mp4","*.m4v","*.mqv","*.dat","*.vcd","*.ogm","*.ogv","*.asf","*.wmv","*.vob","*.mkv","*.ram","*.flv","*.rm","*.ts","*.rmvb","*.dvr-ms","*.m2t","*.m2ts","*.rec","*.f4v","*.hdmov","*.webm","*.vp8"},
                      media_filetypes = audio_filetypes + video_filetypes,
                      subtitle_filetypes = {"*.sub","*.srt","*.ass","*.ssa"};

**Comment by amazingfate** [comment]
I can only list these two video type for now: *.letv, *.hlv
I'll add more if I find.
