### ISSUE TITLE
Missing configuration file editing in Windows

### ISSUE THREAD

**Issue by robin007bond** [u8sand/Baka-MPlayer#96]
First of all, I think Baka-Mplayer is a great GUI for mpv. Unfortunately, I think that a lot of customization options are missing from the GUI. 

The .ini config file is stored in the executable itself, is it possible for people using Windows to configure it themselves? Without repacking the executable?

**Comment by u8sand** [comment]
@robin007bond the .ini file is not stored in the executable; it is right next to the executable, this is for portability. It should be very easy to edit though we try to offer most configuration options in the GUI itself. If there is something in particular you wish to customize please request it.
